# Arrays ( Mutable sequence)

1. Arrays are used to store multiple values in one single variable

2. Arrays are mutable but static.(Size of array cannot be changed).INSERT/DELETE cant be performed in array

In [16]:
import numpy as np

In [17]:
A=np.array([1,2,3,2,4,5,5,6])

In [18]:
A

array([1, 2, 3, 2, 4, 5, 5, 6])

In [19]:
B=np.array(["a","b","c"])

In [20]:
c=np.array([1,"b"])

In [21]:
type(c)

numpy.ndarray

In [22]:
c[0]=1

In [23]:
type(c[0])

numpy.str_

In [24]:
A[0]+A[2]

4

In [25]:
A[0]+c[0]

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

In [34]:
A*A

array([ 1,  4,  9,  4, 16, 25, 25, 36])

In [39]:
A

array([1, 2, 3, 2, 4, 5, 5, 6])

In [35]:
A+A

array([ 2,  4,  6,  4,  8, 10, 10, 12])

In [36]:
A-A

array([0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
A/2

array([0.5, 1. , 1.5, 1. , 2. , 2.5, 2.5, 3. ])

In [38]:
A*2

array([ 2,  4,  6,  4,  8, 10, 10, 12])

In [41]:
v=np.array([9,8,7])

In [42]:
v

array([9, 8, 7])

In [43]:
v.sort()

In [44]:
v

array([7, 8, 9])

In [45]:
# Another package that is available in python
import array as arr
d=arr.array('i',[3,4,5])

In [51]:
d

array('i', [3, 4, 5])

In [52]:
d[0]

3

In [53]:
d.append(8)

In [55]:
d

array('i', [3, 4, 5, 8])

In [56]:
d.pop()

8

In [57]:
d.append("df")

TypeError: an integer is required (got type str)

In [58]:
d.extend([7,8,0,6,4,])

In [59]:
d

array('i', [3, 4, 5, 7, 8, 0, 6, 4])

In [60]:
d.remove(4)

In [61]:
d

array('i', [3, 5, 7, 8, 0, 6, 4])